Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Include:
    - Rakefile
  Exclude:
    - config/initializers/secret_token.rb
    - config.ru
    - db/schema.rb
